name: Issue Triage
on:
  issues:
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const labels = [];
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body.toLowerCase();
            
            if (title.includes('bug') || body.includes('error')) {
              labels.push('bug');
            }
            if (title.includes('feature') || body.includes('request')) {
              labels.push('enhancement');
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels
              });
            }
